// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_WLNnDPRdHoDVLE7t3B62gtHdACfWQD8',
    appId: '1:28465003983:android:3e54cdd6f1cc29960da6ba',
    messagingSenderId: '28465003983',
    projectId: 'fir-auth-activity13',
    storageBucket: 'fir-auth-activity13.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQaBKhLZ1Kv2AyRi2S9jJUMqCWDW4zFBA',
    appId: '1:28465003983:web:00ba587c307bb7ad0da6ba',
    messagingSenderId: '28465003983',
    projectId: 'fir-auth-activity13',
    authDomain: 'fir-auth-activity13.firebaseapp.com',
    storageBucket: 'fir-auth-activity13.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQaBKhLZ1Kv2AyRi2S9jJUMqCWDW4zFBA',
    appId: '1:28465003983:web:0933e0e4cfb6365c0da6ba',
    messagingSenderId: '28465003983',
    projectId: 'fir-auth-activity13',
    authDomain: 'fir-auth-activity13.firebaseapp.com',
    storageBucket: 'fir-auth-activity13.firebasestorage.app',
  );

}